# Generated by Django 5.0 on 2024-01-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('title',), 'verbose_name': 'материал', 'verbose_name_plural': 'материалы'},
        ),
    ]
