# Generated by Django 5.0 on 2023-12-17 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='data_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='data_created',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
