# Generated by Django 5.0 on 2024-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='is_current',
        ),
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='активная версия'),
        ),
    ]
